### ISSUE TITLE
vgg19.npy not found

### ISSUE THREAD

**Issue by jeffin07** [thatbrguy/Dehaze-GAN#15]
While running `python replicate.npy` shows an error No such file or directory: './vgg19.npy'.I have downloaded the checkpoint files specified.

**Comment by thatbrguy** [comment]
You would have to download the VGG19 weights from [here](https://github.com/machrisaa/tensorflow-vgg). The exact procedure is also mentioned in the second step of the instructions of the readme file in this repository.

**Comment by jeffin07** [comment]
@thatbrguy The links are working after I used a proxy. Sorry for the late response
