### ISSUE TITLE
Issue in Inference Mode

### ISSUE THREAD

**Issue by jeffin07** [thatbrguy/Dehaze-GAN#16]
I was trying to do inference using my own images. I used `main.py` file in inference mode also downloaded the checkpoints but while executing `main.py` file I get an error

`tensorflow.python.framework.errors_impl.NotFoundError: Key Discriminator/Final_Layer/Conv/Filter not found in checkpoint
	 [[{{node Save/save/RestoreV2}}]]
`

**Comment by thatbrguy** [comment]
Hey @jeffin07,

In the `README` file, I had mentioned the following:
```
3. For recreating the results reported in the paper, use the repository legacy (for more details refer below). 
This repository is the refactored version of the final model, but it uses newer versions of some TensorFlow operations. 
Those operations are not available in the old saved checkpoints
```
The checkpoint files should work with the code in the `legacy` folder. Do try that out and let me know if it works.

**Comment by jeffin07** [comment]
@thatbrguy I've tried replicate.py in the legacy folder but in replicate.py we can't give our own test images right, the images are taken from A.npy so that's why I tried main.py file. replicate.py runs fine. The problem with that is I cannot use my own test images

**Comment by thatbrguy** [comment]
Hey, sorry for the very late reply. As explained in the `README` file (and in the previous comment), the checkpoint files may not be compatible with the code outside the `legacy` folder.

If you want to perform inference on custom images using the checkpoint files, an easy way to do that is to modify `replicate.py` such that it reads in images rather those `.npy` files. Apologies for the inconvenience.
