### ISSUE TITLE
tensorflow version issue

### ISSUE THREAD

**Issue by SchulerTsang** [thatbrguy/Dehaze-GAN#20]
Hi, I am using tensorflow 2.2.0 gpu it does't work anyway, same situation happend when i using version 1.15.0 any suggestion?

**Comment by thatbrguy** [comment]
Hello, I have not tested this repository with tensorflow 2.x. I'm not sure if it will readily work well with the eager execution mode. I would recommend using tensorflow 1.x for this repo.

I think I used a rather older version of tensorflow when I created this repository. I'm not sure if I remember the exact version. But maybe you could try using a much lower version like 1.4 or 1.7 or 1.9 and seeing if it works. 

I will have try to running the code again on these versions to see what works. Will try to do so when I get the time. Do let me know if you happen to try it out as well. 

I'll keep this issue open for now.

**Comment by thatbrguy** [comment]
Mentioned the TensorFlow version issue in the known issues section of the README file ([link](https://github.com/thatbrguy/Dehaze-GAN#known-issues)). Closing this issue for now.
