### ISSUE TITLE
issue in training

### ISSUE THREAD

**Issue by kritipoddar123** [thatbrguy/Dehaze-GAN#3]
[Errno 2] No such file or directory: 'A_train.npy'

**Comment by ghost** [comment]
same error is occuring as kritipoddar please respond to this @thatbrguy

**Comment by thatbrguy** [comment]
@visenpooja @kritipoddar123 Please set `--custom_data` to `True` if you are providing `--A_dir` and `--B_dir`. It will not ask for `A_train.npy` if it is set to `True`. Let me know if the error persists.

**Comment by ghost** [comment]
so do i have  to run the code in following syntax @thatbrguy  
python3 main.py \
> --A_dir A \
> --B_dir B \
> batch_size 2 \
> epochs 20 \
> --custom_data == True

**Comment by thatbrguy** [comment]
@visenpooja The correct method is:

```
python3 main.py \
    --A_dir=A \
    --B_dir=B \
    --batch_size=2 \
    --epochs=20 \
    --custom_data=True
```

If that does not work, in line 235 of `model.py` you can change `if self.custom_data:` to `if True:` to bypass the issue. This is more of a hacky solution, but it will work all the same.

**Comment by ghost** [comment]
i am getting this error now @thatbrguy 
AttributeError: 'NoneType' object has no attribute 'astype'

**Comment by thatbrguy** [comment]
@visenpooja Should be an issue with your image path. `cv2.imread` is probably not able to find the image and hence returns `None`. Please make sure you place `A_dir` and `B_dir` in the directory where you are executing your code.

**Comment by kritipoddar123** [comment]
I am not able to clone the file.Error says no such file or directory exists.

**Comment by kritipoddar123** [comment]
please reply @thatbrguy/Dehaze-GAN <Dehaze-GAN@noreply.github.com>

**Comment by thatbrguy** [comment]
@kritipoddar123 You may have made a mistake in the execution of the code. 

In any case, looks like there is not an issue/bug with the code itself so I am closing this issue. If you need any help, please explain your error in detail by telling what command you ran and what error it displayed.
