### ISSUE TITLE
The replicate.tar.gz file can't be downloaded

### ISSUE THREAD

**Issue by ravenxrz** [thatbrguy/Dehaze-GAN#4]
The checkpoint file link  seems no longer available. Could you fix it ?

**Comment by ravenxrz** [comment]
I finally download the file after trying a lot of times, and I generate a new link here(https://drive.google.com/open?id=104wMe565-Tr9vfsdSdRcAgoKRjJk_9us) to help those people who can not download this.

经过反复尝试，我终于把这个文件下载下来了。为了帮助那些没能成功下载的人，我生成了一个新的链接：https://drive.google.com/file/d/104wMe565-Tr9vfsdSdRcAgoKRjJk_9us/view

**Comment by thatbrguy** [comment]
Thanks for providing a mirror :) but it looks like the file can be downloaded from the original link without any issues as well. Could be an issue on your side
