### ISSUE TITLE
When I finished the work,the checkpoint is directory

### ISSUE THREAD

**Issue by VV4yne** [thatbrguy/Dehaze-GAN#5]
I have created the 'model/checkpoint' directory. But when i finished the training, an events file was in the 'model/tensorboard' and the 'model/checkpoint' was empty from begining to end.

**Comment by sainatha798** [comment]
change the less than (<) symbol in line 371 of model.py file to greater than(>).I guess that should solve #

**Comment by sainatha798** [comment]
> I have created the 'model/checkpoint' directory. But when i finished the training, an events file was in the 'model/tensorboard' and the 'model/checkpoint' was empty from begining to end.


change the less than (<) symbol in line 371 of model.py file to greater than(>).I guess that should solve #
