### ISSUE TITLE
could Dehaze-GAN apply on image inpainting?

### ISSUE THREAD

**Issue by erhuodaosi** [thatbrguy/Dehaze-GAN#6]
@thatbrguy 
Hi,

I'm sorry to bother you,but I have some questions in the use of this network,could it apply on image inpainting?

Looking Forwarding to receiving your reply.I would very appreciate if you could help me,thank you!

Thanks,

**Comment by thatbrguy** [comment]
Hey @erhuodaosi as long as you create a suitable dataset, yes you can use the same model for image inpainting.

**Comment by erhuodaosi** [comment]
@thatbrguy

Hi，

Thank you for your timely reply!Thank you very much!I would have a try.

Thanks,
